# Generated by Django 3.2.3 on 2021-05-31 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(0, 'Guild Text'), (1, 'Direct Message'), (2, 'Guild Voice'), (3, 'Group Direct Message'), (4, 'Guild Category'), (5, 'Guild News'), (6, 'Guild Store'), (10, 'Guild News Thread'), (11, 'Guild Public Thread'), (12, 'Guild Private Thread'), (13, 'Guild Stage Voice')], default=0)),
                ('position', models.IntegerField(default=0)),
                ('name', models.CharField(default=None, max_length=128, null=True)),
                ('topic', models.CharField(default='', max_length=1024)),
                ('nsfw', models.BooleanField(default=False)),
                ('bitrate', models.IntegerField(default=None, null=True)),
                ('user_limit', models.IntegerField(default=0, verbose_name='User limit of voice channel')),
                ('rate_limit_per_user', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Discord User ID')),
                ('username', models.CharField(default=None, max_length=32, null=True)),
                ('discriminator', models.CharField(default=None, max_length=4, null=True)),
                ('avatar', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('Bot?', models.BooleanField(default=False, verbose_name='Is the user a bot?')),
                ('System User?', models.BooleanField(default=False, verbose_name='Is the user a system user?')),
                ('MFA Enabled?', models.BooleanField(default=False)),
                ('locale', models.CharField(blank=True, default='', max_length=64)),
                ('Verified?', models.BooleanField(default=False, verbose_name='Email on the account verified?')),
                ('email', models.CharField(blank=True, default=None, max_length='128', null=True)),
                ('flags', models.IntegerField(default=0)),
                ('premium_type', models.IntegerField(default=0)),
                ('public_flags', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Discord Guild ID')),
                ('name', models.CharField(default=None, max_length=128, null=True)),
                ('icon', models.CharField(default=None, max_length=64, null=True)),
                ('splash', models.CharField(default=None, max_length=64, null=True)),
                ('discovery_splash', models.CharField(default=None, max_length=64, null=True)),
                ('region', models.CharField(default=None, max_length=16, null=True)),
                ('afk_timeout', models.IntegerField(default=None, null=True, verbose_name='AFK Timeout in Seconds')),
                ('Widget Enabled?', models.BooleanField(default=False, verbose_name='Is the Widget Enabled?')),
                ('verification_level', models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Very High')], default=0)),
                ('default_message_notifications', models.IntegerField(choices=[(0, 'All Messages'), (1, 'Only Mentions')], default=0)),
                ('explicit_content_filter', models.IntegerField(choices=[(0, 'Disabled'), (1, 'Members Without Roles'), (2, 'All Members')], default=0)),
                ('mfa_level', models.IntegerField(choices=[(0, 'None'), (1, 'Elevated')], default=0)),
                ('application', models.PositiveBigIntegerField(default=None, null=True)),
                ('system_channel_flags', models.IntegerField(default=0)),
                ('Large?', models.BooleanField(default=False)),
                ('vanity_url_code', models.CharField(default=None, max_length=64, null=True)),
                ('description', models.CharField(default='', max_length=512)),
                ('banner', models.CharField(default=None, max_length=64, null=True)),
                ('premium_tier', models.IntegerField(choices=[(0, 'None'), (1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3')], default=0)),
                ('premium_subscription_count', models.IntegerField(default=0)),
                ('preferred_locale', models.CharField(default=None, max_length=16, null=True)),
                ('nsfw_level', models.IntegerField(choices=[(0, 'Default'), (1, 'Explicit'), (2, 'Safe'), (3, 'Age Restricted')], default=0)),
                ('afk_channel', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='django_discord.channel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_discord.user')),
                ('public_updates_channel_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_discord.channel')),
                ('rules_channel', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='django_discord.channel')),
                ('system_channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_discord.channel')),
                ('widget_channel', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='django_discord.channel')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='guild',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_discord.guild'),
        ),
        migrations.AddField(
            model_name='channel',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_discord.channel'),
        ),
    ]
